[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip MEC1723N_B0_SZ'

rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabihf"     # Cortex-M4F and Cortex-M7F (with FPU)
